implementation of  new design o n home page for elintegro website
elintegro/dataframe pull request #282
Opened 2021-06-18 04:17 UTC by Rajes-23

2021-06-18 06:40 UTC, Simon-Norris approved these changes

2021-06-18 14:39 UTC, Rabindra5 requested changes

2021-06-18 14:39 UTC, Rabindra5 commented on dataframe/src/main/groovy/com/elintegro/erf/widget/vue/ComboboxVue.groovy
> -                  small-chips
Don't remove any properties from Widget, make them overwritable from descriptor.

2021-06-18 14:53 UTC, Rabindra5 approved these changes

2021-06-22 06:07 UTC, Simon-Norris approved these changes

2021-07-01 08:58 UTC, merged